### PR TITLE
Portuguese (pt_PT) update

### PR DESCRIPTION
**Pull request by pedro-mendonca**

### CODE REVIEW

**Comment by ruhanirabin** [comment]
Pedro I have requested at wordpress/polyglots to have you as an editor for **pt_PT** language. Once it is approved, you can post directly to https://translate.wordpress.org/locale/pt/default/wp-plugins/wp-optimize

I am closing this for now

**Comment by pedro-mendonca** [comment]
Hi, don't bother, I'm already Editor and pushed the translation to the repo.
I just pushed here as you keep also translations on the /languages subfolder.

**Comment by ruhanirabin** [comment]
oh okay 👍

**Comment by pedro-mendonca** [comment]
As GlotPress is still growing, I usually prefer to keep some translations locally because sometimes apear old strings with no author. Some bugs that keep apearing. I prefer redundancy, for now... :)

**Comment by ruhanirabin** [comment]
Can i still merge this to my develop branch @pedro-mendonca ?

**Comment by pedro-mendonca** [comment]
Yes of course. I'll definetly keep it in a personal branch if you don't want to include it, but I've done it for you to include it :)
Feel free to keep it or not :+1:

**Pull request merged**
