### PR TITLE
Strings cleanup

### PR DESCRIPTION
**Pull request by pedro-mendonca**
Remove unnecessary spaces from strings
Moved necessary spaces out of string to avoid translation errors

### CODE REVIEW

**Comment by pedro-mendonca** [comment]
@ruhanirabin 
About this PR https://github.com/pedro-mendonca/WP-Optimize/commit/d917f07cbadad514218de87bdc0ffbf230e8a6b9
As an example, in portuguese it should be "Base de dados %s optimizada!", this is why I've putted the DBNAME inside the string.

**Comment by pedro-mendonca** [comment]
@ruhanirabin 
In https://github.com/pedro-mendonca/WP-Optimize/commit/e7e3217457983956e40e8f4f2dc0c88eb0247033 I've added single and plural versions for these strings, using the same coding pattern you've used in `%s Table` and `%s Record`.

**Comment by pedro-mendonca** [comment]
Added commas to database name in https://github.com/pedro-mendonca/WP-Optimize/commit/30c29ecf0a04eb8797b996cccfe4d3378083e395

This is to improve readability and to keep coherent with other references to dbname where commas were already used

**Comment by pedro-mendonca** [comment]
Here https://github.com/pedro-mendonca/WP-Optimize/commit/0e9c519fe2b618f14b5d639cf140de91b3e233de just changed from %s to %d on quantity strings (only numbers)

**Comment by pedro-mendonca** [comment]
Here https://github.com/pedro-mendonca/WP-Optimize/commit/3629c992b947438b178a38846e0858ae3370b761 I've merged strings together and include variable.
It improves readability and understanding the context for translation, making the string one complete sentence with some variable in between. Best practice for translatable strings.

**Comment by pedro-mendonca** [comment]
In this https://github.com/pedro-mendonca/WP-Optimize/commit/273c1776b1431f53d3b6f3533e1f07c403d9618c I've commented the piece of code ' - ' that will only be necessary if the code below will also be uncommented.

**Comment by ruhanirabin** [comment]
Hi Pedro .. thanks for the changes, do you know any simpler way to migrate the language files? Can you help on this?

**Comment by pedro-mendonca** [comment]
I can help doing a find/replace on the most obvious strings, cleaning empty spaces, joining strings with variables etc.
But I believe that some of the strings shoud be marked as fuzzy so that their translators can check them.

**Comment by pedro-mendonca** [comment]
Just found another string that I think that would be better as one complete sentence, for the benefit of it's translations:
"Keep last "+X+" "+"weeks data".
Seeing a complete sentence changes a lot in most of the time, makes the context clear.
For this I'm not sure how to clean it, as the function for the weeks number is a bit more intrincated. I'll leave it for later.

**Comment by pedro-mendonca** [comment]
@ruhanirabin 
As I've started a propper cleanup of other languages .po files, cleaning empty spaces, etc, I'm thinking in joining some other strings like "Next schedule"+":". This also is a better practice because you can choose the best way to put it in your own language. As an example, despite it's correct for most languages, in French there should be an empy space like this "Next schedule :"
So, in most cases this is a simple join, do you think I can do this also?

**Comment by ruhanirabin** [comment]
@pedro-mendonca yes you can :) :+1:

**Comment by pedro-mendonca** [comment]
Ok, I'll do it before continue she .po files cleanup.
Can you take care of the above "Keep last "+X+" "+"weeks data".?

**Comment by ruhanirabin** [comment]
@pedro-mendonca "Keep last "+X+" "+"weeks data" - no need to touch that part now.

**Comment by pedro-mendonca** [comment]
@ruhanirabin 
I'm done for now. I think all the changes are complete now, from the strings cleanup to the .po files updates.
If you any question on this, please ask. :)

**Comment by pedro-mendonca** [comment]
@ruhanirabin I've made it to concatenate those extra strings I've asked you to take care.
It's done, now only need to update .po language files to concatenate the same strings.

**Pull request merged**
